version: '3'

services:
  web:
    restart: on-failure
    container_name: oauthweb
    build: ./
    working_dir: /code/github_oauth
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./:/code:rw
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: github_oauth.settings
    ports:
      - "8000:8000"

  db:
    container_name: db
    restart: always
    image: postgres:10-alpine
    volumes:
      - ./.dbdata:/var/lib/postgresql:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: oauth
      POSTGRES_PASSWORD: oauth
      POSTGRES_DB: oauth

